spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketing_service
    username: Test
    password: password
    driverClassName: org.postgresql.Driver

  flyway:
    enabled: true
    user: Test
    password: password
    schemas: public
    url: jdbc:postgresql://localhost:5432/ticketing_service